---
- name: Install Java
  apt:
    name: openjdk-17-jre-headless
    state: present
    update_cache: yes

- name: Create Jenkins user
  user:
    name: jenkins
    home: /var/lib/jenkins
    shell: /bin/bash
    create_home: yes

- name: Create Jenkins installation directory
  file:
    path: /opt/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    mode: "0755"

- name: Download Jenkins WAR
  get_url:
    url: https://get.jenkins.io/war-stable/latest/jenkins.war
    dest: /opt/jenkins/jenkins.war
    mode: "0644"

- name: Set Jenkins directory ownership
  file:
    path: /opt/jenkins
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Create Jenkins Home Directory
  file:
    path: /var/lib/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    mode: "0755"

- name: Create Jenkins Plugins Directory
  file:
    path: /var/lib/jenkins/plugins
    state: directory
    owner: jenkins
    group: jenkins
    mode: "0755"

- name: Copy Plugins List
  copy:
    src: plugins.txt
    dest: /var/lib/jenkins/plugins.txt
    owner: jenkins
    group: jenkins
  notify: restart jenkins

- name: Deploy Master JCasC Configuration
  template:
    src: master-casc.yaml.j2
    dest: /var/lib/jenkins/casc.yaml
    owner: jenkins
    group: jenkins
    mode: "0644"
  notify: restart jenkins

- name: Configure Jenkins Environment
  template:
    src: jenkins.env.j2
    dest: /etc/default/jenkins

- name: Create Jenkins systemd service
  copy:
    dest: /etc/systemd/system/jenkins.service
    content: |
      [Unit]
      Description=Jenkins
      After=network.target

      [Service]
      User=jenkins
      WorkingDirectory=/opt/jenkins
      ExecStart=/usr/bin/java -jar /opt/jenkins/jenkins.war --httpPort=8080
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Start Jenkins Service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Install Jenkins Plugins
  import_tasks: plugins.yml
