
---
jenkins_admin_user: AniketWakekar
jenkins_admin_password: 123

dockerhub_username: aniketwakekar
dockerhub_password: "[-----DOCKERHUB_PASSWORD-----]"

gmail_id: aniketwakekar239@gmail.com
gmail_app_password: "[-----GMAIL_APP_PASSWORD-----]"

github_url: https://github.com/Wakekar

jenkins_url: "http://65.2.151.66]:8080"

sonarqube_url: "http://65.2.151.66:9000"

nexus_url: "http://65.2.151.66:8081"
